# Generated by Django 6.1.1 on 2026-09-26 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bio_alter_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emoji_status',
            field=models.CharField(default='🕷️', max_length=8),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('birthday', "Tug'ilgan kun")], default='birthday', max_length=9)),
                ('emoji', models.CharField(default='🎂', max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('night', 'Night'), ('day', 'Day')], default='night', max_length=5)),
                ('accent', models.CharField(default='#8b5cf6', max_length=20)),
                ('send_on_enter', models.BooleanField(default=True)),
                ('show_birthday_banner', models.BooleanField(default=True)),
                ('wallpaper', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=60)),
                ('slot_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('hidden', 'Yashirilgan')], default='active', max_length=8)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='unique_account_label_per_user')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'user'), name='unique_contact_per_user')],
            },
        ),
    ]
