# Generated by Django 6.1.1 on 2026-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_attachment_call_folder_chat_is_bot_chat_is_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.CharField(blank=True, default='', help_text='Frontend yuborgan vaqtincha id (dedup uchun).', max_length=40),
        ),
    ]
